import numpy as np
import cv2
#im = cv2.imread('test.jpg')
im = cv2.imread('2.jpg')
#kernel = np.ones((2,2),np.uint8)
#dilation = cv2.dilate(im,kernel,iterations = 1)
#im = dilation
#blur = cv2.blur(im,(10,10))
imgray = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(imgray, 240, 255, 0)
kernel = np.ones((2,2),np.uint8)
erosion = cv2.erode(thresh,kernel,iterations = 1)
blur = cv2.blur(erosion,(2,2))
ret,thresh2= cv2.threshold(blur,240,255,0)
#cv2.namedWindow('thresh', cv2.WINDOW_NORMAL)
#cv2.imshow('thresh',thresh)
#cv2.waitKey(0)
#cv2.destroyAllWindows()
#imgray = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
#ret, thresh = cv2.threshold(imgray, 127, 255, 0)
contours, hierarchy = cv2.findContours(thresh2, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
cv2.drawContours(im, contours, -1, (0,255,0), 1)
cv2.namedWindow('image', cv2.WINDOW_NORMAL)
cv2.imshow('image',im)
cv2.waitKey(0)
cv2.destroyAllWindows()  